//
// This file is part of the RonDB REST API Server
// Copyright (c) 2022 Hopsworks AB
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: internal/grpcsrv/rdrs.proto

package grpcsrv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column string `protobuf:"bytes,1,opt,name=Column,proto3" json:"Column,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *FilterProto) Reset() {
	*x = FilterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterProto) ProtoMessage() {}

func (x *FilterProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterProto.ProtoReflect.Descriptor instead.
func (*FilterProto) Descriptor() ([]byte, []int) {
	return file_internal_grpcsrv_rdrs_proto_rawDescGZIP(), []int{0}
}

func (x *FilterProto) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *FilterProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReadColumnProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column         string  `protobuf:"bytes,1,opt,name=Column,proto3" json:"Column,omitempty"`
	DataReturnType *string `protobuf:"bytes,2,opt,name=DataReturnType,proto3,oneof" json:"DataReturnType,omitempty"`
}

func (x *ReadColumnProto) Reset() {
	*x = ReadColumnProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadColumnProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadColumnProto) ProtoMessage() {}

func (x *ReadColumnProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadColumnProto.ProtoReflect.Descriptor instead.
func (*ReadColumnProto) Descriptor() ([]byte, []int) {
	return file_internal_grpcsrv_rdrs_proto_rawDescGZIP(), []int{1}
}

func (x *ReadColumnProto) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ReadColumnProto) GetDataReturnType() string {
	if x != nil && x.DataReturnType != nil {
		return *x.DataReturnType
	}
	return ""
}

type PKReadRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DB          string             `protobuf:"bytes,1,opt,name=DB,proto3" json:"DB,omitempty"`
	Table       string             `protobuf:"bytes,2,opt,name=Table,proto3" json:"Table,omitempty"`
	Filters     []*FilterProto     `protobuf:"bytes,3,rep,name=Filters,proto3" json:"Filters,omitempty"`
	ReadColumns []*ReadColumnProto `protobuf:"bytes,4,rep,name=ReadColumns,proto3" json:"ReadColumns,omitempty"`
	OperationID *string            `protobuf:"bytes,5,opt,name=OperationID,proto3,oneof" json:"OperationID,omitempty"`
}

func (x *PKReadRequestProto) Reset() {
	*x = PKReadRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKReadRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKReadRequestProto) ProtoMessage() {}

func (x *PKReadRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKReadRequestProto.ProtoReflect.Descriptor instead.
func (*PKReadRequestProto) Descriptor() ([]byte, []int) {
	return file_internal_grpcsrv_rdrs_proto_rawDescGZIP(), []int{2}
}

func (x *PKReadRequestProto) GetDB() string {
	if x != nil {
		return x.DB
	}
	return ""
}

func (x *PKReadRequestProto) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *PKReadRequestProto) GetFilters() []*FilterProto {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *PKReadRequestProto) GetReadColumns() []*ReadColumnProto {
	if x != nil {
		return x.ReadColumns
	}
	return nil
}

func (x *PKReadRequestProto) GetOperationID() string {
	if x != nil && x.OperationID != nil {
		return *x.OperationID
	}
	return ""
}

type PKReadResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp int32 `protobuf:"varint,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *PKReadResponseProto) Reset() {
	*x = PKReadResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKReadResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKReadResponseProto) ProtoMessage() {}

func (x *PKReadResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKReadResponseProto.ProtoReflect.Descriptor instead.
func (*PKReadResponseProto) Descriptor() ([]byte, []int) {
	return file_internal_grpcsrv_rdrs_proto_rawDescGZIP(), []int{3}
}

func (x *PKReadResponseProto) GetResp() int32 {
	if x != nil {
		return x.Resp
	}
	return 0
}

type BatchRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req int32 `protobuf:"varint,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *BatchRequestProto) Reset() {
	*x = BatchRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequestProto) ProtoMessage() {}

func (x *BatchRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequestProto.ProtoReflect.Descriptor instead.
func (*BatchRequestProto) Descriptor() ([]byte, []int) {
	return file_internal_grpcsrv_rdrs_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRequestProto) GetReq() int32 {
	if x != nil {
		return x.Req
	}
	return 0
}

type BatchResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp int32 `protobuf:"varint,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *BatchResponseProto) Reset() {
	*x = BatchResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponseProto) ProtoMessage() {}

func (x *BatchResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcsrv_rdrs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponseProto.ProtoReflect.Descriptor instead.
func (*BatchResponseProto) Descriptor() ([]byte, []int) {
	return file_internal_grpcsrv_rdrs_proto_rawDescGZIP(), []int{5}
}

func (x *BatchResponseProto) GetResp() int32 {
	if x != nil {
		return x.Resp
	}
	return 0
}

var File_internal_grpcsrv_rdrs_proto protoreflect.FileDescriptor

var file_internal_grpcsrv_rdrs_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x72, 0x76, 0x2f, 0x72, 0x64, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x69, 0x0a, 0x0f, 0x52, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x2b, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x12, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x44, 0x42, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x44, 0x42, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x52, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x25,
	0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70,
	0x22, 0x25, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x32, 0x78, 0x0a, 0x0f, 0x52, 0x6f, 0x6e, 0x44, 0x42, 0x52, 0x65, 0x73, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x06, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x12, 0x13,
	0x2e, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x2e, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x05, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x12, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x2f, 0x2e, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_grpcsrv_rdrs_proto_rawDescOnce sync.Once
	file_internal_grpcsrv_rdrs_proto_rawDescData = file_internal_grpcsrv_rdrs_proto_rawDesc
)

func file_internal_grpcsrv_rdrs_proto_rawDescGZIP() []byte {
	file_internal_grpcsrv_rdrs_proto_rawDescOnce.Do(func() {
		file_internal_grpcsrv_rdrs_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpcsrv_rdrs_proto_rawDescData)
	})
	return file_internal_grpcsrv_rdrs_proto_rawDescData
}

var file_internal_grpcsrv_rdrs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_grpcsrv_rdrs_proto_goTypes = []interface{}{
	(*FilterProto)(nil),         // 0: FilterProto
	(*ReadColumnProto)(nil),     // 1: ReadColumnProto
	(*PKReadRequestProto)(nil),  // 2: PKReadRequestProto
	(*PKReadResponseProto)(nil), // 3: PKReadResponseProto
	(*BatchRequestProto)(nil),   // 4: BatchRequestProto
	(*BatchResponseProto)(nil),  // 5: BatchResponseProto
}
var file_internal_grpcsrv_rdrs_proto_depIdxs = []int32{
	0, // 0: PKReadRequestProto.Filters:type_name -> FilterProto
	1, // 1: PKReadRequestProto.ReadColumns:type_name -> ReadColumnProto
	2, // 2: RonDBRestServer.PKRead:input_type -> PKReadRequestProto
	4, // 3: RonDBRestServer.Batch:input_type -> BatchRequestProto
	3, // 4: RonDBRestServer.PKRead:output_type -> PKReadResponseProto
	5, // 5: RonDBRestServer.Batch:output_type -> BatchResponseProto
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpcsrv_rdrs_proto_init() }
func file_internal_grpcsrv_rdrs_proto_init() {
	if File_internal_grpcsrv_rdrs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpcsrv_rdrs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcsrv_rdrs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadColumnProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcsrv_rdrs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKReadRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcsrv_rdrs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKReadResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcsrv_rdrs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcsrv_rdrs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_grpcsrv_rdrs_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_internal_grpcsrv_rdrs_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpcsrv_rdrs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcsrv_rdrs_proto_goTypes,
		DependencyIndexes: file_internal_grpcsrv_rdrs_proto_depIdxs,
		MessageInfos:      file_internal_grpcsrv_rdrs_proto_msgTypes,
	}.Build()
	File_internal_grpcsrv_rdrs_proto = out.File
	file_internal_grpcsrv_rdrs_proto_rawDesc = nil
	file_internal_grpcsrv_rdrs_proto_goTypes = nil
	file_internal_grpcsrv_rdrs_proto_depIdxs = nil
}
